"""add task recurrence columns

Revision ID: d34c0a0cde34
Revises: 60e73d562cf8
Create Date: 2026-06-07 14:15:51.050239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34c0a0cde34'
down_revision = '60e73d562cf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # On PostgreSQL, op.add_column does not auto-create a named ENUM type the way
    # create_table does, so create it first (checkfirst keeps this a no-op on
    # backends without standalone enum types, e.g. SQLite). Mirrors the drop in downgrade().
    recurrence_enum = sa.Enum('none', 'daily', 'weekly', 'monthly', name='recurrenceenum')
    recurrence_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('recurrence', recurrence_enum, server_default='none', nullable=False))
    op.add_column('tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(
        'fk_tasks_parent_task_id_tasks', 'tasks', 'tasks',
        ['parent_task_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_parent_task_id_tasks', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'recurrence')
    # Drop the enum type created for the recurrence column (Postgres only;
    # a no-op on backends without standalone enum types).
    sa.Enum(name='recurrenceenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

